config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :categories, only: [:index, :show]
   mount ChinaCity::Engine => '/china_city'

  namespace :dashboard do
    get '/' => "base#index"
    get 'base/index'
    get 'setting' => "setting#index"
    resources :categories do
      member do
        get :conditions_list
      end
    end
    resources :conditions
    resources :condition_values
    resources :accessories do
      member do
        patch :publish
        patch :time_due
        patch :hold
      end
    end
    resources :users do
      member do
        patch :toggle_visible
      end
    end
  end

  namespace :plugin do
    get '/' => 'base#index'
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:create] do
      post :login, on: :collection
      delete :sign_out, on: :collection
    end
  end

  resource :session, controller: :session
  resource :registration, only: [:new, :create], controller: :registration


  root 'welcome#index'


end

app/models/accessory.rb
# == Schema Information
#
# Table name: accessories
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  count         :integer
#  category_id   :integer
#  category_name :string(255)
#  user_id       :integer
#  state         :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#


require 'jbuilder'
class Accessory < ApplicationRecord
  include AASM
  ES_INDEX = "foobar"
  ES_TYPE = "accessories"

  STATE_MAP = {published: "已发布", pending: "未发布", hold: "暂存" }

  STATE_MAP.keys.each do |s|
    scope s, proc { where(state: s) }
  end

  QUANTITY_LIST = {
    "cate100": "全新",
    "cate90": "九成新",
    "cate80": "八成新",
    "cate70": "五成新",
  }

  belongs_to :user
  belongs_to :category

  has_many :accessory_conditions, dependent: :destroy
  has_many :conditions, through: :accessory_conditions
  has_many :accessory_condition_values, dependent: :destroy
  has_many :condition_values, through: :accessory_condition_values
  has_many :image_assets, as: :attachable

  validates :count, presence: { message: '配件数量不能空' }
  validates :price, presence: { message: '配件单价不能空' }
  accepts_nested_attributes_for :image_assets
  after_save :es_index
  before_save :accessory_reinit
  after_destroy :remove_es_index

  aasm :state do
    state :pending, initial: true
    state :publishing
    state :hold
    state :expired

    event :publish do
      transitions from: :pending, to: :published
    end

    event :time_due do
      transitions from: [:published], to: :expired
    end

    event :hold do
      transitions from: [:pending, :published], to: :hold
    end
  end


  def title
    [self.category_name || self.category.try(:name), self.count].join " "
  end


  # elastic search related methods
  def es_index
    request = $esclient.es_request ES_INDEX, ES_TYPE, self.id, self.es_body
    $esclient.es_index request
  end

  def remove_es_index
    $esclient.es_remove ES_INDEX, ES_TYPE, self.id
  end

  class << self
    def es_query_name_like_and_condition_match(name, condition_matches)
      matches = [{
        match: {
          name: {
            "query": name,
            "fuzziness": 2
          }
        }
      }
      ]

      condition_matches.each do |k,  v|
        match = {
          match: {
            "#{k}": {
              "query": v,
              "fuzziness": 0
            }
          }
        }

        matches.push match
      end

      Jbuilder.encode do |json|
        json.query do
          json.bool do
            json.must do
              json.array! matches
            end
          end
        end
      end
    end
  end

  def es_body
    body = {
      description: self.description,
      count: self.count,
      category_name: self.category_name,
      category_pinyin: self.category.try(:pinyin),
    }
    self.conditions.each do |condition|
      body[condition.pinyin.downcase] = self.condition_values.of_condition(condition).first.try(:pinyin).try(:downcase)
      body[condition.name] = self.condition_values.of_condition(condition).first.try(:name)
    end

    body
  end

  def accessory_reinit
    self.category_name = self.category.try :name
    self.count ||= 10
  end
end

app/controllers/dashboard/accessories_controller.rb
class Dashboard::AccessoriesController < Dashboard::BaseController
  before_action :find_accessory, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    if params[:state]
      @accessories = policy_scope(Accessory).send(params[:state]).includes(:user).page(params[:page]).order("id DESC")
    else
      @accessories = policy_scope(Accessory).includes(:user).page(params[:page]).order("id DESC")
    end
  end

  def show
  end

  def edit
  end

  def new
    @accessory = Accessory.new
    @accessory.category_id = Category.default_category.id
    @accessory.count = 20
    @accessory.price = 50
    @accessory.quanlity = Accessory::QUANTITY_LIST.keys.first

    3.times do
      @accessory.image_assets.build
    end
  end

  def create
    @accessory = current_user.accessories.new accessory_param
    if @accessory.save
      redirect_to dashboard_accessories_path, notice: '配件上传成功'
    else
      render :new
    end
  end

  %w(hold publish time_due).each do |method|
    define_method(method) do
      authorize @accessory
      if @accessory.send "#{method}!"
        redirect_to dashboard_categories_path, notice: "修改成功"
      else
        render :edit
      end
    end
  end

  def destroy
    if @accessory.destroy
      notice = "删除成功"
    else
      notice = "删除失败"
    end
    redirect_to dashboard_accessories_path, notice: notice
  end

  def update
    authorize @accessory
    if @accessory.update_attributes accessory_param
      redirect_to dashboard_categories_path, notice: "分类修改成功"
    else
      render :edit
    end
  end

  protected
  def find_accessory
    @accessory = Accessory.find params[:id]
  end

  def accessory_param
    params.required(:accessory).permit!
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!

  def index
  end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < Dashboard::BaseController
  before_action :find_category, only: [:edit, :update, :destroy, :conditions_list]

  def index
    @default_category = Category.find_by(id: params[:category_id]) || Category.find_by(name: "CPU")
    @default_condition = Condition.find_by(id: params[:condition_id]) || @default_category.conditions.first
    @default_condition_value = ConditionValue.find_by(id: params[:condition_value_id]) || @default_condition.try(:condition_values).try(:first) || []
    @categories = Category.order('id desc').page params[:page]
    @conditions = @default_category.conditions
    @condition_values = @default_condition.try(:condition_values) || []
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = policy_scope(Category).new category_param
      authorize @category
      if @category.save
        render js: "window.location.reload()"
      else
        render js: "$.notify('#{@category.errors.full_messages.first}', 'error')"
    end
  end

  def edit
  end

  def conditions_list
    @conditions = @category.conditions
    @grouped_condition_values = {}
    @conditions.each do |c|
      @grouped_condition_values[c] = c.condition_values
    end
    render layout: false
  end

  def update
    authorize @category
    if @category.update_attributes category_param
      redirect_to dashboard_categories_path, notice: "分类修改成功"
    else
      render :edit
    end
  end

  def destroy
    authorize @category

    if @category.conditions.count > 0
      redirect_to dashboard_categories_path, notice: "分类已被使用,暂时不能删除"
      return
    end

    if @category.destroy
      redirect_to dashboard_categories_path, notice: "分类删除成功"
    else
      redirect_to dashboard_categories_path, notice: "分类删除失败, #{@category.errors.full_messages.first}"
    end
  end

  private
  def category_param
    params.require(:category).permit!
  end

  def find_category
    @category  = policy_scope(Category).find params[:id]
  end
end

app/controllers/dashboard/condition_values_controller.rb
class Dashboard::ConditionValuesController < Dashboard::BaseController
  before_filter :find_condition_value, only: [:edit, :update, :destroy]

  def create
    @condition_value = policy_scope(ConditionValue).new condition_value_param

      authorize @condition_value
      if @condition_value.save
        render js: "window.location.reload()"
      else
        render js: "alert('#{@condition_value.errors.full_messages.first}')"
    end
  end

  def destroy
    authorize @condition_value

    if @condition_value.condition_value_values.count > 0
      render js: "$.notify('当前分类指标已经使用', 'error')"
      return
    end

    if @condition_value.destroy
      redirect_to dashboard_categories_path, notice: "模型删除成功"
      render js: "alert('#{@condition_value.errors.full_messages.first}')"
    else
      redirect_to dashboard_categories_path, notice: "模型删除失败"
    end
  end

  def update
    authorize @condition_value
    if @condition_value.update_attributes condition_value_param
      redirect_to dashboard_categories_path, notice: "分类修改成功"
    else
      render :edit
    end
  end

  private
  def condition_value_param
    params.require(:condition_value).permit!
  end

  def find_condition_value
    @condition_value  = policy_scope(ConditionValue).find params[:id]
  end
end

app/controllers/dashboard/conditions_controller.rb
class Dashboard::ConditionsController < Dashboard::BaseController
  before_filter :find_condition, only: [:edit, :update, :destroy]

  def create
    @condition = policy_scope(Condition).new condition_param

      authorize @condition
      if @condition.save
        render js: "window.location.reload()"
      else
        render js: "alert('#{@condition.errors.full_messages.first}')"
    end
  end

  def destroy
    authorize @condition

    if @condition.condition_values.count > 0
      render js: "$.notify('当前分类指标已经使用', 'error')"
      return
    end

    if @condition.destroy
      redirect_to dashboard_categories_path, notice: "模型删除成功"
      render js: "alert('#{@condition.errors.full_messages.first}')"
      
    else
      redirect_to dashboard_categories_path, notice: "模型删除失败"
    end
  end

  def update
    authorize @condition
    if @condition.update_attributes condition_param
      redirect_to dashboard_categories_path, notice: "分类修改成功"
    else
      render :edit
    end
  end

  private
  def condition_param
    params.require(:condition).permit!
  end

  def find_condition
    @condition  = policy_scope(Condition).find params[:id]
  end
end

app/controllers/dashboard/setting_controller.rb
class Dashboard::SettingController < Dashboard::BaseController
  def index
    redirect_to dashboard_categories_path
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  before_action :find_user, only: [:edit, :update, :destroy, :toggle_visible]

  respond_to :html

  def index
    if params[:admin]
      @users = policy_scope(User).admin.page params[:page]
    else
      @users = policy_scope(User).normal_user.page params[:page]
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new user_params
    authorize @user
    if @user.save && @user.make_admin!
      flash[:notice] = "用户创建成功"
    else
      flash[:alert] = "用户创建失败，#{@user.errors.full_messages.first}"
    end

    redirect_to dashboard_users_path(admin: true)
  end

  def toggle_visible
    authorize @user, :update?
    @user.update_column :visible, !@user.visible
    render :js => "window.location.reload();"
  end


  def update
    authorize @user
    if @user.update_attributes user_params
      flash[:notice] = "用户修改成功"
    else
      flash[:alert] = "用户修改失败，#{@user.errors.full_messages.first}"
    end
    redirect_to edit_dashboard_user_path(@user)
  end

  private
  def find_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/dashboard/accessories_helper.rb
module Dashboard::AccessoriesHelper
end

app/helpers/dashboard/base_helper.rb
module Dashboard::BaseHelper
end

app/helpers/dashboard/entities_helper.rb
module Dashboard::EntitiesHelper
end

app/helpers/dashboard/materials_helper.rb
module Dashboard::MaterialsHelper
end

app/helpers/dashboard/setting_helper.rb
module Dashboard::SettingHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard/vendors_helper.rb
module Dashboard::VendorsHelper
end

app/views/dashboard/accessories/_form.html.haml
.panel.panel-default
  .panel-body
    = simple_form_for [:dashboard, @accessory], input_html: { multipart: true } do |f|
      = f.input :category_id, as: :select, collection: Category.all, include_blank: false, label: '分类'
      #condition_value_list
      = f.input :count, as: :integer, label: '数量', input_html: { placeholder: 10 }
      = f.input :price, as: :integer, label: '单价', input_html: { placeholder: 10 }
      = f.input :quanlity, as: :select, label: '成色', collection: Accessory::QUANTITY_LIST.invert, include_blank: false

      .form-group
        %label.control-label 取货地点

        %p.address
          = @accessory.user ? @accessory.user.address : current_user.address
        %p
          = link_to "修改取货地址", edit_dashboard_user_path(@accessory.user || current_user), target: "_blank"

      .row
        = f.simple_fields_for :image_assets do |image|
          .col-md-3.accessory_pic_holder
            = image.input :file,  as: :file, label: "图片#{cycle(%w(一 二 三))}", input_html: { data: 'filename-placement', accept: ".png, .jpg, .jpeg"}

      = f.submit "上传", class: 'btn btn-success'


    :javascript
      var load_condition_list = function(){
        $('#condition_value_list').load('/dashboard/categories/' + $('#accessory_category_id').val() + '/conditions_list');
      }
      $(document).on('ready turbolinks:load').ready(function(){
        $('#accessory_category_id').on('change', load_condition_list);
        $(document).on('click', '#condition_value_list label', function(){ $(this).toggleClass('active_label_condition')});
        load_condition_list();
      })

app/views/dashboard/accessories/index.html.haml
%ul.list-inline.bg-info.label_bg
  %li
    %h4
      %label.label.label-bg{class: 'label-success' }
        = link_to "全部", dashboard_accessories_path
  - Accessory::STATE_MAP.each do |key, value|
    %li
      %h4
        %label.label{class: cycle('label-warning') }
          = link_to value, dashboard_accessories_path(state: key)

= link_to gly_icon(:plus) +"新配件", new_dashboard_accessory_path(admin: true), {"class" => 'btn btn-default btn-primary'}


%table.table
  %thead
    %th ID
    %th 分类
    %th 数量
    %th 单价
    %th 联系方式
    %th 交货地点
    %th
  %tbody
    - @accessories.each do |a|
      %tr
        %td= a.id
        %td= a.category_name || a.category.name
        %td
          = a.count
          个
        %td
          = a.price
          元
        %td
          = a.user.name
          =a.user.mobile
        %td= a.user.address
        %th
          - if policy(:accessory).publish? && (a.pending?  || a.hold?)
            = link_to gly_icon(:play), publish_dashboard_accessory_path(a), method: :patch, data: { confirm: "确定要公布此信息？" }

          - if policy(:accessory).hold? && a.pending?
            = link_to gly_icon(:pause), hold_dashboard_accessory_path(a), method: :patch, data: { confirm: "确定要撤销此信息？" }


          = link_to gly_icon(:pencil), edit_dashboard_accessory_path(a)
          = link_to gly_icon(:remove), dashboard_accessory_path(a), method: :delete, data: { confirm: "确定要删除此配件？" }

= paginate @accessories

app/views/dashboard/accessories/new.html.haml
= render :partial => "form"

app/views/dashboard/accessories/show.html.haml
%h1 Dashboard::Accessories#show
%p Find me in app/views/dashboard/accessories/show.html.haml