config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :categories, only: [:index, :show]
   mount ChinaCity::Engine => '/china_city'

  namespace :dashboard do
    get '/' => "base#index"
    get 'base/index'
    get 'setting' => "setting#index"
    resources :categories do
      member do
        get :conditions_list
      end
    end
    resources :conditions
    resources :condition_values
    resources :accessories do
      member do
        patch :publish
        patch :time_due
        patch :hold
      end
    end
    resources :users do
      member do
        patch :toggle_visible
      end
    end
  end

  namespace :plugin do
    get '/' => 'base#index'
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:create] do
      post :login, on: :collection
      delete :sign_out, on: :collection
    end
  end

  resource :session, controller: :session
  resource :registration, only: [:new, :create], controller: :registration


  root 'welcome#index'


end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  pinyin     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#

class Category < ApplicationRecord
  include Pinyinable

  acts_as_paranoid

  scope :default_category,  proc { where("name = 'CPU'").first }

  has_many :entities
  has_many :conditions
  has_many :condition_values

  validates :name, presence: { message: '分类名称不能空' }
end

app/controllers/dashboard/accessories_controller.rb
class Dashboard::AccessoriesController < Dashboard::BaseController
  before_action :find_accessory, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    if params[:state]
      @accessories = policy_scope(Accessory).send(params[:state]).includes(:user).page(params[:page]).order("id DESC")
    else
      @accessories = policy_scope(Accessory).includes(:user).page(params[:page]).order("id DESC")
    end
  end

  def show
  end

  def edit
  end

  def new
    @accessory = Accessory.new
    @accessory.category_id = Category.default_category.id
    @accessory.count = 20
    @accessory.price = 50
    @accessory.quanlity = Accessory::QUANTITY_LIST.keys.first

    3.times do
      @accessory.image_assets.build
    end
  end

  def create
    @accessory = current_user.accessories.new accessory_param
    if @accessory.save
      redirect_to dashboard_accessories_path, notice: '配件上传成功'
    else
      render :new
    end
  end

  %w(hold publish time_due).each do |method|
    define_method(method) do
      authorize @accessory
      if @accessory.send "#{method}!"
        redirect_to dashboard_categories_path, notice: "修改成功"
      else
        render :edit
      end
    end
  end

  def destroy
    if @accessory.destroy
      notice = "删除成功"
    else
      notice = "删除失败"
    end
    redirect_to dashboard_accessories_path, notice: notice
  end

  def update
    authorize @accessory
    if @accessory.update_attributes accessory_param
      redirect_to dashboard_categories_path, notice: "分类修改成功"
    else
      render :edit
    end
  end

  protected
  def find_accessory
    @accessory = Accessory.find params[:id]
  end

  def accessory_param
    params.required(:accessory).permit!
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!

  def index
  end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < Dashboard::BaseController
  before_action :find_category, only: [:edit, :update, :destroy, :conditions_list]

  def index
    @default_category = Category.find_by(id: params[:category_id]) || Category.find_by(name: "CPU")
    @default_condition = Condition.find_by(id: params[:condition_id]) || @default_category.conditions.first
    @default_condition_value = ConditionValue.find_by(id: params[:condition_value_id]) || @default_condition.try(:condition_values).try(:first) || []
    @categories = Category.order('id desc').page params[:page]
    @conditions = @default_category.conditions
    @condition_values = @default_condition.try(:condition_values) || []
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = policy_scope(Category).new category_param
      authorize @category
      if @category.save
        render js: "window.location.reload()"
      else
        render js: "$.notify('#{@category.errors.full_messages.first}', 'error')"
    end
  end

  def edit
  end

  def conditions_list
    @conditions = @category.conditions
    @grouped_condition_values = {}
    @conditions.each do |c|
      @grouped_condition_values[c] = c.condition_values
    end
    render layout: false
  end

  def update
    authorize @category
    if @category.update_attributes category_param
      redirect_to dashboard_categories_path, notice: "分类修改成功"
    else
      render :edit
    end
  end

  def destroy
    authorize @category

    if @category.conditions.count > 0
      redirect_to dashboard_categories_path, notice: "分类已被使用,暂时不能删除"
      return
    end

    if @category.destroy
      redirect_to dashboard_categories_path, notice: "分类删除成功"
    else
      redirect_to dashboard_categories_path, notice: "分类删除失败, #{@category.errors.full_messages.first}"
    end
  end

  private
  def category_param
    params.require(:category).permit!
  end

  def find_category
    @category  = policy_scope(Category).find params[:id]
  end
end

app/controllers/dashboard/condition_values_controller.rb
class Dashboard::ConditionValuesController < Dashboard::BaseController
  before_filter :find_condition_value, only: [:edit, :update, :destroy]

  def create
    @condition_value = policy_scope(ConditionValue).new condition_value_param

      authorize @condition_value
      if @condition_value.save
        render js: "window.location.reload()"
      else
        render js: "alert('#{@condition_value.errors.full_messages.first}')"
    end
  end

  def destroy
    authorize @condition_value

    if @condition_value.condition_value_values.count > 0
      render js: "$.notify('当前分类指标已经使用', 'error')"
      return
    end

    if @condition_value.destroy
      redirect_to dashboard_categories_path, notice: "模型删除成功"
      render js: "alert('#{@condition_value.errors.full_messages.first}')"
    else
      redirect_to dashboard_categories_path, notice: "模型删除失败"
    end
  end

  def update
    authorize @condition_value
    if @condition_value.update_attributes condition_value_param
      redirect_to dashboard_categories_path, notice: "分类修改成功"
    else
      render :edit
    end
  end

  private
  def condition_value_param
    params.require(:condition_value).permit!
  end

  def find_condition_value
    @condition_value  = policy_scope(ConditionValue).find params[:id]
  end
end

app/controllers/dashboard/conditions_controller.rb
class Dashboard::ConditionsController < Dashboard::BaseController
  before_filter :find_condition, only: [:edit, :update, :destroy]

  def create
    @condition = policy_scope(Condition).new condition_param

      authorize @condition
      if @condition.save
        render js: "window.location.reload()"
      else
        render js: "alert('#{@condition.errors.full_messages.first}')"
    end
  end

  def destroy
    authorize @condition

    if @condition.condition_values.count > 0
      render js: "$.notify('当前分类指标已经使用', 'error')"
      return
    end

    if @condition.destroy
      redirect_to dashboard_categories_path, notice: "模型删除成功"
      render js: "alert('#{@condition.errors.full_messages.first}')"
      
    else
      redirect_to dashboard_categories_path, notice: "模型删除失败"
    end
  end

  def update
    authorize @condition
    if @condition.update_attributes condition_param
      redirect_to dashboard_categories_path, notice: "分类修改成功"
    else
      render :edit
    end
  end

  private
  def condition_param
    params.require(:condition).permit!
  end

  def find_condition
    @condition  = policy_scope(Condition).find params[:id]
  end
end

app/controllers/dashboard/setting_controller.rb
class Dashboard::SettingController < Dashboard::BaseController
  def index
    redirect_to dashboard_categories_path
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  before_action :find_user, only: [:edit, :update, :destroy, :toggle_visible]

  respond_to :html

  def index
    if params[:admin]
      @users = policy_scope(User).admin.page params[:page]
    else
      @users = policy_scope(User).normal_user.page params[:page]
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new user_params
    authorize @user
    if @user.save && @user.make_admin!
      flash[:notice] = "用户创建成功"
    else
      flash[:alert] = "用户创建失败，#{@user.errors.full_messages.first}"
    end

    redirect_to dashboard_users_path(admin: true)
  end

  def toggle_visible
    authorize @user, :update?
    @user.update_column :visible, !@user.visible
    render :js => "window.location.reload();"
  end


  def update
    authorize @user
    if @user.update_attributes user_params
      flash[:notice] = "用户修改成功"
    else
      flash[:alert] = "用户修改失败，#{@user.errors.full_messages.first}"
    end
    redirect_to edit_dashboard_user_path(@user)
  end

  private
  def find_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/dashboard/accessories_helper.rb
module Dashboard::AccessoriesHelper
end

app/helpers/dashboard/base_helper.rb
module Dashboard::BaseHelper
end

app/helpers/dashboard/entities_helper.rb
module Dashboard::EntitiesHelper
end

app/helpers/dashboard/materials_helper.rb
module Dashboard::MaterialsHelper
end

app/helpers/dashboard/setting_helper.rb
module Dashboard::SettingHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard/vendors_helper.rb
module Dashboard::VendorsHelper
end

app/views/dashboard/categories/_form.html.haml
= simple_form_for [:dashboard, @category], class: 'form form-horizontal', multipart: true  do |f|
  = f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" } ,label: "上级分类"
  = f.input :name, label: "分类名称"
  = f.submit f.object.persisted? ? "修改" : "增加", class: 'btn btn-primary btn-default'

app/views/dashboard/categories/_list.html.haml
%ul.list-group.col-md-2.categories_list.well
  %li.list-group-item
    %label.label-default.label.add_category_label
      = gly_icon(:plus)
  - @categories.each do |c|
    %li.list-group-item{class: c == @default_category ? 'active' : ''}
      = link_to c.name, dashboard_categories_path(category_id: c.id)
      .operation_panel
        = link_to gly_icon(:pencil), edit_dashboard_category_path(c)
        = link_to gly_icon(:remove), dashboard_category_path(c), method: :delete, data: { confirm: "删除此模型？" }


%ul.list-group.col-md-2.categories_list.well
  %li.list-group-item
    %label.label-default.label.add_condition_label
      = gly_icon(:plus)
  - @conditions.each do |c|
    %li.list-group-item{class: c == @default_condition ? 'active' : ''}
      = link_to c.name, dashboard_categories_path(category_id: c.category_id, condition_id: c.id)
      .operation_panel
        = link_to gly_icon(:pencil), edit_dashboard_condition_path(c)
        = link_to gly_icon(:remove), dashboard_condition_path(c), method: :delete, data: { confirm: "删除此模型？" }


%ul.list-group.col-md-2.categories_list.well
  %li.list-group-item
    %label.label-default.label.add_condition_value_label
      = gly_icon(:plus)
  - @condition_values.each do |c|
    %li.list-group-item{class: c == @default_condition_value ? 'active' : ''}
      = link_to c.name, dashboard_categories_path(category_id: c.category_id, condition_id: c.condition_id, condition_value_id: c.id)
      .operation_panel
        = link_to gly_icon(:pencil), edit_dashboard_condition_value_path(c)
        = link_to gly_icon(:remove), dashboard_condition_value_path(c), method: :delete, data: { confirm: "删除此模型？" }

.modal#newCategory{role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    = form_for [:dashboard, Category.new], remote: true do |f|
      .modal-content
        .modal-header
          %span 配件分类
          %button.close{data: { dismiss: 'modal' }, 'aria-label': 'Close'}
            %span{'aria-hidden': 'true'}
              &times;
        .modal-body
          名称
          = f.text_field :name
        .modal-footer
          = f.submit "新建", class: 'btn'

.modal#newCondition{role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    = form_for [:dashboard, Condition.new(category: @default_category)], remote: true do |f|
      .modal-content
        .modal-header
          %span #{@default_category.name}
          %button.close{data: { dismiss: 'modal' }, 'aria-label': 'Close'}
            %span{'aria-hidden': 'true'}
              &times;
        .modal-body
          指标
          = f.text_field :name, label: "指标"
          = f.hidden_field :category_id
        .modal-footer
          = f.submit "增加", class: 'btn'

.modal#newConditionValue{role: 'dialog', tabindex: '-1'}
  .modal-dialog{role: 'document'}
    = form_for [:dashboard, ConditionValue.new(condition: @default_condition, category: @default_category)], remote: true do |f|
      .modal-content
        .modal-header
          %span #{@default_category.name} #{@default_condition.try :name}
          %button.close{data: { dismiss: 'modal' }, 'aria-label': 'Close'}
            %span{'aria-hidden': 'true'}
              &times;
        .modal-body
          指标值
          = f.text_field :name, label: "指标值"
          = f.hidden_field :category_id
          = f.hidden_field :condition_id
        .modal-footer
          = f.submit "新建", class: 'btn'

:javascript
  $(document).on('ready turbolinks:load', function(){
    $('.add_category_label').click(function() {
      $('#newCategory').modal({});
    });

    $('.add_condition_label').click(function() {
      $('#newCondition').modal({});
    });

    $('.add_condition_value_label').click(function() {
      $('#newConditionValue').modal({});
    });
  })

app/views/dashboard/categories/conditions_list.html.haml
%table.table.grouped_condition_values_table
  - @grouped_condition_values.each do |k, v|
    %tr
      %td= k.name
      %td
        - v.each do |value|
          %label.label_condition
            = value.name
            %span.remove_condtion_value
              = gly_icon('ok-sign')

app/views/dashboard/categories/index.html.haml
= render :partial => "layouts/dashboard_setting_tab"

= render :partial => "list"