config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :categories, only: [:index, :show]
   mount ChinaCity::Engine => '/china_city'

  namespace :dashboard do
    get '/' => "base#index"
    get 'base/index'
    get 'setting' => "setting#index"
    resources :categories do
      member do
        get :conditions_list
      end
    end
    resources :conditions
    resources :condition_values
    resources :accessories do
      member do
        patch :publish
        patch :time_due
        patch :hold
      end
    end
    resources :users do
      member do
        patch :toggle_visible
      end
    end
  end

  namespace :plugin do
    get '/' => 'base#index'
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:create] do
      post :login, on: :collection
      delete :sign_out, on: :collection
    end
  end

  resource :session, controller: :session
  resource :registration, only: [:new, :create], controller: :registration


  root 'welcome#index'


end

app/views/widgets/_header.html.haml
.container
  %header.nav.navbar
    .navbar-header
      = image_tag "logo.png", style: "height: 30px"
    %nav
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to "录入配件", new_dashboard_accessory_path, data: { 'no-turbolinks': true }
        %li
          = link_to "我的配件", dashboard_accessories_path, data: { 'no-turbolinks': true }
        %li
          = link_to "搜索配件", new_dashboard_accessory_path, data: { 'no-turbolinks': true }
        - if user_signed_in?
          %li
            = link_to "退出登录", session_path, method: :delete
          %li
            - if params[:controller] == "welcome"
              = link_to "我的后台", dashboard_path, data: { 'no-turbolinks': true }
            - else
              = link_to "回到首页", root_path

        - else
          %li
            = link_to "登录", new_session_path, data: { 'no_turbolink': true }
          %li
            = link_to "注册", new_registration_path, data: { 'no_turbolink': true }

app/views/widgets/_message.html.haml
- flash.keys.each do |k, v|
  .uk-alert.uk-alert-large{"data-uk-alert" => true}
    = flash[k]

app/views/widgets/_session_message.html.haml
- flash.keys.each do |k, v|
  .alert.alert-large{"data-uk-alert" => true}
    = flash[k]

app/views/widgets/_sidebar.html.haml
%ul
  %li
    = link_to gly_icon(:home) + "我的首页", dashboard_path
  %li
    = link_to gly_icon("cubes") + "我的模型", dashboard_entities_path
  - if policy(Vendor.new)
    %li= link_to gly_icon(:user) + "材料管理", dashboard_materials_path
    %li= link_to gly_icon(:cubes) + "材料商管理", dashboard_vendors_path
    %li.uk-nav-divider
    %li= link_to gly_icon(:cubes) +"用户管理", dashboard_users_path
    %li= link_to gly_icon(:cubes) +"管理员管理", dashboard_users_path(admin: true)

  %li 个人设置
  %li
    = link_to gly_icon(:key) + "修改密码", ""
  %li
    = link_to gly_icon(:gears) + "个人设置", ""