config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :categories, only: [:index, :show]
   mount ChinaCity::Engine => '/china_city'

  namespace :dashboard do
    get '/' => "base#index"
    get 'base/index'
    get 'setting' => "setting#index"
    resources :categories do
      member do
        get :conditions_list
      end
    end
    resources :conditions
    resources :condition_values
    resources :accessories do
      member do
        patch :publish
        patch :time_due
        patch :hold
      end
    end
    resources :users do
      member do
        patch :toggle_visible
      end
    end
  end

  namespace :plugin do
    get '/' => 'base#index'
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:create] do
      post :login, on: :collection
      delete :sign_out, on: :collection
    end
  end

  resource :session, controller: :session
  resource :registration, only: [:new, :create], controller: :registration


  root 'welcome#index'


end

app/views/layouts/_dashboard_setting_tab.html.haml
%ul.nav.nav-tabs
  %li{role: :presentation, class: nav_li_class('categories', 'setting') }
    = link_to "分类设置" , dashboard_categories_path

app/views/layouts/_message.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/dashboard.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title= Setting.cn_name
    = stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'dashboard', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .container-fluid
      %nav.nav.navbar-inverse.navbar-fixed-top
        .container
          .navbar-header
            = link_to gly_icon(:globe) + Setting.cn_name, root_path, class: 'navbar-brand', data: { 'no-turbolinks': true }

          %ul.navbar-nav.nav.pull-right
            %li= link_to current_user.identity, edit_dashboard_user_path(current_user)
            %li= link_to "退出", session_path, method: :delete

    .container.dashboard{class: controller_name }
      .sidebar
        %ul.nav.nav-sidebar
          %li{class: nav_li_class('users') }
            = link_to gly_icon(:user) + "配件列表", dashboard_accessories_path
          - if policy(User).list?
            %li{class: nav_li_class('users') }
              = link_to gly_icon(:user) + "用户列表", dashboard_users_path

          - if policy(:setting).show?
            %li
              = link_to gly_icon(:asterisk) + "设置", dashboard_setting_path

        %ul.nav.nav-sidebar
          %li.active
      .main_content
        .col-md-12
          = render :partial => "layouts/message"
          = yield

app/views/layouts/plugin.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    :coffee
      window.name_config = #{EntityConfig.name_config.to_json}
      window.material_config = #{EntityConfig.material_config.to_json}
      window.attributes_config = #{EntityConfig.attributes_config.to_json}

    = javascript_include_tag 'plugin'
    = stylesheet_link_tag 'plugin'
    = csrf_meta_tag

  %body{'ng-app' => 'building'}
    .uk-container.uk-container-center.su-container{'ng-controller' => 'Main'}
      .data-channel
        %input#data_transfer_channel{type: 'hidden'}

      .uk-grid#model_profile
        .uk-width-1-3{"ng-show" => "current_entity.type"}
          %img{'ng-src' => "{{current_entity.thumbnail_src}}", 'width' => 123, 'class' => "data-uk-margin"}
        .uk-width-2-3{"ng-show" => "current_entity.type"}
          = form_tag "", method: "post", class: "uk-form" do
            %input.uk-form-small.uk-margin-bottom.uk-float-right.fc-name-field{'ng-model' => "readable_name(current_entity.name)", "ng-editable" => false}
            .uk-clearfix
          #action_bar
            %button.uk-button.uk-button-small.uk-primary.uk-float-right.uk-margin-right{'ng-click' => "bridge('save_current_component_definition')", "ng-disabled" => "{{!current_entity.name && current_entity.type == 'component_definition'}}"} 保存
            %button.uk-button.uk-button-small.uk-primary.uk-float-right.uk-margin-right{'ng-click' => "goto_page('/attributes')", "ng-disabled" => "{{current_entity.type == 'component_definition'}}"} 属性
        .uk-width-3-3{"ng-show" => "!current_entity.type"}
          .uk-alert.uk-alert-success.uk-text-center 请选择一个模型

      #models
        %div{"ui-view" => true}

      -##ad
        -#.uk-panel
          -#.ad-item
            -#= image_tag asset_path('mianzhuan.jpg'), height: 60, width: 60, class: 'uk-border-rounded'
          -#.ad-item
            -#= image_tag asset_path('shicai.jpg'), height: 60, width: 60, class: 'uk-border-rounded'
          -#.ad-item
            -#= image_tag asset_path('mianzhuan.jpg'), height: 60, width: 60, class: 'uk-border-rounded'
          -#.ad-item
            -#= image_tag asset_path('shicai.jpg'), height: 60, width: 60, class: 'uk-border-rounded'
          -#.ad-item
            -#= image_tag asset_path('mianzhuan.jpg'), height: 60, width: 60, class: 'uk-border-rounded'

      #user_profile.uk-container
        %div{"ng-show" => "!CurrentUser.isLogin()"}
          %button.uk-button.uk-button-primary.uk-float-right.uk-margin-right{"ui-sref" => "register"} 我要注册
          %button.uk-button.uk-button-primary.uk-float-right.uk-margin-right{"ui-sref" => "login"} 我要登录

        %div{"ng-show" => "CurrentUser.isLogin()"}
          %button.uk-button.uk-button-primary{"ng-click" => "sign_out()"} 退出

app/views/layouts/session.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title SuBackend
    = stylesheet_link_tag    'session', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'session', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .container
      .row
        .col-md-6.col-md-offset-3.session_form
          = yield
          = render :partial => "layouts/message"

app/views/layouts/website.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title 构建中国
    = stylesheet_link_tag    'website', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'website', 'data-turbolinks-track' => false
    = csrf_meta_tags
  %body
    = render :partial => "widgets/header"
    = yield